// All ISO 4217 currencies as static members for convenient access.
// Usage: Currency.usd, Currency.eur, etc.

extension Currency {
    public static let aed = Currency(code: "AED", symbol: "د.إ")
    public static let afn = Currency(code: "AFN", symbol: "؋")
    public static let allLek = Currency(code: "ALL", symbol: "L")
    public static let amd = Currency(code: "AMD", symbol: "֏")
    public static let ang = Currency(code: "ANG", symbol: "ƒ")
    public static let aoa = Currency(code: "AOA", symbol: "Kz")
    public static let ars = Currency(code: "ARS", symbol: "$")
    public static let aud = Currency(code: "AUD", symbol: "A$")
    public static let awg = Currency(code: "AWG", symbol: "ƒ")
    public static let azn = Currency(code: "AZN", symbol: "₼")
    public static let bam = Currency(code: "BAM", symbol: "KM")
    public static let bbd = Currency(code: "BBD", symbol: "Bds$")
    public static let bdt = Currency(code: "BDT", symbol: "৳")
    public static let bgn = Currency(code: "BGN", symbol: "лв")
    public static let bhd = Currency(code: "BHD", symbol: ".د.ب", minorUnits: 3)
    public static let bif = Currency(code: "BIF", symbol: "FBu", minorUnits: 0)
    public static let bmd = Currency(code: "BMD", symbol: "$")
    public static let bnd = Currency(code: "BND", symbol: "B$")
    public static let bob = Currency(code: "BOB", symbol: "Bs.")
    public static let brl = Currency(code: "BRL", symbol: "R$")
    public static let bsd = Currency(code: "BSD", symbol: "$")
    public static let btn = Currency(code: "BTN", symbol: "Nu.")
    public static let bwp = Currency(code: "BWP", symbol: "P")
    public static let byn = Currency(code: "BYN", symbol: "Br")
    public static let bzd = Currency(code: "BZD", symbol: "BZ$")
    public static let cad = Currency(code: "CAD", symbol: "CA$")
    public static let cdf = Currency(code: "CDF", symbol: "FC")
    public static let chf = Currency(code: "CHF", symbol: "CHF")
    public static let clp = Currency(code: "CLP", symbol: "$", minorUnits: 0)
    public static let cny = Currency(code: "CNY", symbol: "¥")
    public static let cop = Currency(code: "COP", symbol: "$")
    public static let crc = Currency(code: "CRC", symbol: "₡")
    public static let cup = Currency(code: "CUP", symbol: "$")
    public static let cve = Currency(code: "CVE", symbol: "$")
    public static let czk = Currency(code: "CZK", symbol: "Kč")
    public static let djf = Currency(code: "DJF", symbol: "Fdj", minorUnits: 0)
    public static let dkk = Currency(code: "DKK", symbol: "kr")
    public static let dop = Currency(code: "DOP", symbol: "RD$")
    public static let dzd = Currency(code: "DZD", symbol: "د.ج")
    public static let egp = Currency(code: "EGP", symbol: "E£")
    public static let ern = Currency(code: "ERN", symbol: "Nfk")
    public static let etb = Currency(code: "ETB", symbol: "Br")
    public static let eur = Currency(code: "EUR", symbol: "€")
    public static let fjd = Currency(code: "FJD", symbol: "FJ$")
    public static let fkp = Currency(code: "FKP", symbol: "£")
    public static let gbp = Currency(code: "GBP", symbol: "£")
    public static let gel = Currency(code: "GEL", symbol: "₾")
    public static let ghs = Currency(code: "GHS", symbol: "GH₵")
    public static let gip = Currency(code: "GIP", symbol: "£")
    public static let gmd = Currency(code: "GMD", symbol: "D")
    public static let gnf = Currency(code: "GNF", symbol: "FG", minorUnits: 0)
    public static let gtq = Currency(code: "GTQ", symbol: "Q")
    public static let gyd = Currency(code: "GYD", symbol: "GY$")
    public static let hkd = Currency(code: "HKD", symbol: "HK$")
    public static let hnl = Currency(code: "HNL", symbol: "L")
    public static let hrk = Currency(code: "HRK", symbol: "kn")
    public static let htg = Currency(code: "HTG", symbol: "G")
    public static let huf = Currency(code: "HUF", symbol: "Ft")
    public static let idr = Currency(code: "IDR", symbol: "Rp")
    public static let ils = Currency(code: "ILS", symbol: "₪")
    public static let inr = Currency(code: "INR", symbol: "₹")
    public static let iqd = Currency(code: "IQD", symbol: "ع.د", minorUnits: 3)
    public static let irr = Currency(code: "IRR", symbol: "﷼")
    public static let isk = Currency(code: "ISK", symbol: "kr", minorUnits: 0)
    public static let jmd = Currency(code: "JMD", symbol: "J$")
    public static let jod = Currency(code: "JOD", symbol: "JD", minorUnits: 3)
    public static let jpy = Currency(code: "JPY", symbol: "¥", minorUnits: 0)
    public static let kes = Currency(code: "KES", symbol: "KSh")
    public static let kgs = Currency(code: "KGS", symbol: "сом")
    public static let khr = Currency(code: "KHR", symbol: "៛")
    public static let kmf = Currency(code: "KMF", symbol: "CF", minorUnits: 0)
    public static let kpw = Currency(code: "KPW", symbol: "₩")
    public static let krw = Currency(code: "KRW", symbol: "₩", minorUnits: 0)
    public static let kwd = Currency(code: "KWD", symbol: "د.ك", minorUnits: 3)
    public static let kyd = Currency(code: "KYD", symbol: "$")
    public static let kzt = Currency(code: "KZT", symbol: "₸")
    public static let lak = Currency(code: "LAK", symbol: "₭")
    public static let lbp = Currency(code: "LBP", symbol: "ل.ل")
    public static let lkr = Currency(code: "LKR", symbol: "Rs")
    public static let lrd = Currency(code: "LRD", symbol: "L$")
    public static let lsl = Currency(code: "LSL", symbol: "L")
    public static let lyd = Currency(code: "LYD", symbol: "ل.د", minorUnits: 3)
    public static let mad = Currency(code: "MAD", symbol: "MAD")
    public static let mdl = Currency(code: "MDL", symbol: "L")
    public static let mga = Currency(code: "MGA", symbol: "Ar")
    public static let mkd = Currency(code: "MKD", symbol: "ден")
    public static let mmk = Currency(code: "MMK", symbol: "K")
    public static let mnt = Currency(code: "MNT", symbol: "₮")
    public static let mop = Currency(code: "MOP", symbol: "MOP$")
    public static let mru = Currency(code: "MRU", symbol: "UM")
    public static let mur = Currency(code: "MUR", symbol: "₨")
    public static let mvr = Currency(code: "MVR", symbol: "Rf")
    public static let mwk = Currency(code: "MWK", symbol: "MK")
    public static let mxn = Currency(code: "MXN", symbol: "MX$")
    public static let myr = Currency(code: "MYR", symbol: "RM")
    public static let mzn = Currency(code: "MZN", symbol: "MT")
    public static let nad = Currency(code: "NAD", symbol: "N$")
    public static let ngn = Currency(code: "NGN", symbol: "₦")
    public static let nio = Currency(code: "NIO", symbol: "C$")
    public static let nok = Currency(code: "NOK", symbol: "kr")
    public static let npr = Currency(code: "NPR", symbol: "₨")
    public static let nzd = Currency(code: "NZD", symbol: "NZ$")
    public static let omr = Currency(code: "OMR", symbol: "ر.ع.", minorUnits: 3)
    public static let pab = Currency(code: "PAB", symbol: "B/.")
    public static let pen = Currency(code: "PEN", symbol: "S/.")
    public static let pgk = Currency(code: "PGK", symbol: "K")
    public static let php = Currency(code: "PHP", symbol: "₱")
    public static let pkr = Currency(code: "PKR", symbol: "₨")
    public static let pln = Currency(code: "PLN", symbol: "zł")
    public static let pyg = Currency(code: "PYG", symbol: "₲", minorUnits: 0)
    public static let qar = Currency(code: "QAR", symbol: "ر.ق")
    public static let ron = Currency(code: "RON", symbol: "lei")
    public static let rsd = Currency(code: "RSD", symbol: "din.")
    public static let rub = Currency(code: "RUB", symbol: "₽")
    public static let rwf = Currency(code: "RWF", symbol: "RF", minorUnits: 0)
    public static let sar = Currency(code: "SAR", symbol: "ر.س")
    public static let sbd = Currency(code: "SBD", symbol: "SI$")
    public static let scr = Currency(code: "SCR", symbol: "₨")
    public static let sdg = Currency(code: "SDG", symbol: "ج.س.")
    public static let sek = Currency(code: "SEK", symbol: "kr")
    public static let sgd = Currency(code: "SGD", symbol: "S$")
    public static let shp = Currency(code: "SHP", symbol: "£")
    public static let sle = Currency(code: "SLE", symbol: "Le")
    public static let sos = Currency(code: "SOS", symbol: "Sh")
    public static let srd = Currency(code: "SRD", symbol: "Sr$")
    public static let ssp = Currency(code: "SSP", symbol: "£")
    public static let stn = Currency(code: "STN", symbol: "Db")
    public static let svc = Currency(code: "SVC", symbol: "₡")
    public static let syp = Currency(code: "SYP", symbol: "£S")
    public static let szl = Currency(code: "SZL", symbol: "E")
    public static let thb = Currency(code: "THB", symbol: "฿")
    public static let tjs = Currency(code: "TJS", symbol: "SM")
    public static let tmt = Currency(code: "TMT", symbol: "T")
    public static let tnd = Currency(code: "TND", symbol: "د.ت", minorUnits: 3)
    public static let top = Currency(code: "TOP", symbol: "T$")
    public static let `try` = Currency(code: "TRY", symbol: "₺")
    public static let ttd = Currency(code: "TTD", symbol: "TT$")
    public static let twd = Currency(code: "TWD", symbol: "NT$")
    public static let tzs = Currency(code: "TZS", symbol: "TSh")
    public static let uah = Currency(code: "UAH", symbol: "₴")
    public static let ugx = Currency(code: "UGX", symbol: "USh", minorUnits: 0)
    public static let usd = Currency(code: "USD", symbol: "$")
    public static let uyu = Currency(code: "UYU", symbol: "$U")
    public static let uzs = Currency(code: "UZS", symbol: "сўм")
    public static let ves = Currency(code: "VES", symbol: "Bs.S")
    public static let vnd = Currency(code: "VND", symbol: "₫", minorUnits: 0)
    public static let vuv = Currency(code: "VUV", symbol: "VT", minorUnits: 0)
    public static let wst = Currency(code: "WST", symbol: "WS$")
    public static let xaf = Currency(code: "XAF", symbol: "FCFA", minorUnits: 0)
    public static let xcd = Currency(code: "XCD", symbol: "EC$")
    public static let xof = Currency(code: "XOF", symbol: "CFA", minorUnits: 0)
    public static let xpf = Currency(code: "XPF", symbol: "₣", minorUnits: 0)
    public static let yer = Currency(code: "YER", symbol: "﷼")
    public static let zar = Currency(code: "ZAR", symbol: "R")
    public static let zmw = Currency(code: "ZMW", symbol: "ZK")
    public static let zwl = Currency(code: "ZWL", symbol: "Z$")

    /// All known currencies.
    public static let allCurrencies: [Currency] = [
        .aed, .afn, .allLek, .amd, .ang, .aoa, .ars, .aud, .awg, .azn,
        .bam, .bbd, .bdt, .bgn, .bhd, .bif, .bmd, .bnd, .bob, .brl,
        .bsd, .btn, .bwp, .byn, .bzd,
        .cad, .cdf, .chf, .clp, .cny, .cop, .crc, .cup, .cve, .czk,
        .djf, .dkk, .dop, .dzd,
        .egp, .ern, .etb, .eur,
        .fjd, .fkp,
        .gbp, .gel, .ghs, .gip, .gmd, .gnf, .gtq, .gyd,
        .hkd, .hnl, .hrk, .htg, .huf,
        .idr, .ils, .inr, .iqd, .irr, .isk,
        .jmd, .jod, .jpy,
        .kes, .kgs, .khr, .kmf, .kpw, .krw, .kwd, .kyd, .kzt,
        .lak, .lbp, .lkr, .lrd, .lsl, .lyd,
        .mad, .mdl, .mga, .mkd, .mmk, .mnt, .mop, .mru, .mur, .mvr, .mwk, .mxn, .myr, .mzn,
        .nad, .ngn, .nio, .nok, .npr, .nzd,
        .omr,
        .pab, .pen, .pgk, .php, .pkr, .pln, .pyg,
        .qar,
        .ron, .rsd, .rub, .rwf,
        .sar, .sbd, .scr, .sdg, .sek, .sgd, .shp, .sle, .sos, .srd, .ssp, .stn, .svc, .syp, .szl,
        .thb, .tjs, .tmt, .tnd, .top, .try, .ttd, .twd, .tzs,
        .uah, .ugx, .usd, .uyu, .uzs,
        .ves, .vnd, .vuv,
        .wst,
        .xaf, .xcd, .xof, .xpf,
        .yer,
        .zar, .zmw, .zwl,
    ]
}
