// All ISO 4217 currencies as static members for convenient access.
// Usage: Currency.usd, Currency.eur, etc.

extension Currency {
    public static let aed = Currency(code: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham")
    public static let afn = Currency(code: "AFN", symbol: "؋", name: "Afghan Afghani")
    public static let allLek = Currency(code: "ALL", symbol: "L", name: "Albanian Lek")
    public static let amd = Currency(code: "AMD", symbol: "֏", name: "Armenian Dram")
    public static let ang = Currency(code: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder")
    public static let aoa = Currency(code: "AOA", symbol: "Kz", name: "Angolan Kwanza")
    public static let ars = Currency(code: "ARS", symbol: "$", name: "Argentine Peso")
    public static let aud = Currency(code: "AUD", symbol: "A$", name: "Australian Dollar")
    public static let awg = Currency(code: "AWG", symbol: "ƒ", name: "Aruban Florin")
    public static let azn = Currency(code: "AZN", symbol: "₼", name: "Azerbaijani Manat")
    public static let bam = Currency(code: "BAM", symbol: "KM", name: "Bosnia-Herzegovina Convertible Mark")
    public static let bbd = Currency(code: "BBD", symbol: "Bds$", name: "Barbadian Dollar")
    public static let bdt = Currency(code: "BDT", symbol: "৳", name: "Bangladeshi Taka")
    public static let bgn = Currency(code: "BGN", symbol: "лв", name: "Bulgarian Lev")
    public static let bhd = Currency(code: "BHD", symbol: ".د.ب", name: "Bahraini Dinar", minorUnits: 3)
    public static let bif = Currency(code: "BIF", symbol: "FBu", name: "Burundian Franc", minorUnits: 0)
    public static let bmd = Currency(code: "BMD", symbol: "$", name: "Bermudan Dollar")
    public static let bnd = Currency(code: "BND", symbol: "B$", name: "Brunei Dollar")
    public static let bob = Currency(code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano")
    public static let brl = Currency(code: "BRL", symbol: "R$", name: "Brazilian Real")
    public static let bsd = Currency(code: "BSD", symbol: "$", name: "Bahamian Dollar")
    public static let btn = Currency(code: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum")
    public static let bwp = Currency(code: "BWP", symbol: "P", name: "Botswanan Pula")
    public static let byn = Currency(code: "BYN", symbol: "Br", name: "Belarusian Ruble")
    public static let bzd = Currency(code: "BZD", symbol: "BZ$", name: "Belize Dollar")
    public static let cad = Currency(code: "CAD", symbol: "CA$", name: "Canadian Dollar")
    public static let cdf = Currency(code: "CDF", symbol: "FC", name: "Congolese Franc")
    public static let chf = Currency(code: "CHF", symbol: "CHF", name: "Swiss Franc")
    public static let clp = Currency(code: "CLP", symbol: "$", name: "Chilean Peso", minorUnits: 0)
    public static let cny = Currency(code: "CNY", symbol: "¥", name: "Chinese Yuan")
    public static let cop = Currency(code: "COP", symbol: "$", name: "Colombian Peso")
    public static let crc = Currency(code: "CRC", symbol: "₡", name: "Costa Rican Colón")
    public static let cup = Currency(code: "CUP", symbol: "$", name: "Cuban Peso")
    public static let cve = Currency(code: "CVE", symbol: "$", name: "Cape Verdean Escudo")
    public static let czk = Currency(code: "CZK", symbol: "Kč", name: "Czech Koruna")
    public static let djf = Currency(code: "DJF", symbol: "Fdj", name: "Djiboutian Franc", minorUnits: 0)
    public static let dkk = Currency(code: "DKK", symbol: "kr", name: "Danish Krone")
    public static let dop = Currency(code: "DOP", symbol: "RD$", name: "Dominican Peso")
    public static let dzd = Currency(code: "DZD", symbol: "د.ج", name: "Algerian Dinar")
    public static let egp = Currency(code: "EGP", symbol: "E£", name: "Egyptian Pound")
    public static let ern = Currency(code: "ERN", symbol: "Nfk", name: "Eritrean Nakfa")
    public static let etb = Currency(code: "ETB", symbol: "Br", name: "Ethiopian Birr")
    public static let eur = Currency(code: "EUR", symbol: "€", name: "Euro")
    public static let fjd = Currency(code: "FJD", symbol: "FJ$", name: "Fijian Dollar")
    public static let fkp = Currency(code: "FKP", symbol: "£", name: "Falkland Islands Pound")
    public static let gbp = Currency(code: "GBP", symbol: "£", name: "British Pound")
    public static let gel = Currency(code: "GEL", symbol: "₾", name: "Georgian Lari")
    public static let ghs = Currency(code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi")
    public static let gip = Currency(code: "GIP", symbol: "£", name: "Gibraltar Pound")
    public static let gmd = Currency(code: "GMD", symbol: "D", name: "Gambian Dalasi")
    public static let gnf = Currency(code: "GNF", symbol: "FG", name: "Guinean Franc", minorUnits: 0)
    public static let gtq = Currency(code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal")
    public static let gyd = Currency(code: "GYD", symbol: "GY$", name: "Guyanaese Dollar")
    public static let hkd = Currency(code: "HKD", symbol: "HK$", name: "Hong Kong Dollar")
    public static let hnl = Currency(code: "HNL", symbol: "L", name: "Honduran Lempira")
    public static let hrk = Currency(code: "HRK", symbol: "kn", name: "Croatian Kuna")
    public static let htg = Currency(code: "HTG", symbol: "G", name: "Haitian Gourde")
    public static let huf = Currency(code: "HUF", symbol: "Ft", name: "Hungarian Forint")
    public static let idr = Currency(code: "IDR", symbol: "Rp", name: "Indonesian Rupiah")
    public static let ils = Currency(code: "ILS", symbol: "₪", name: "Israeli New Shekel")
    public static let inr = Currency(code: "INR", symbol: "₹", name: "Indian Rupee")
    public static let iqd = Currency(code: "IQD", symbol: "ع.د", name: "Iraqi Dinar", minorUnits: 3)
    public static let irr = Currency(code: "IRR", symbol: "﷼", name: "Iranian Rial")
    public static let isk = Currency(code: "ISK", symbol: "kr", name: "Icelandic Króna", minorUnits: 0)
    public static let jmd = Currency(code: "JMD", symbol: "J$", name: "Jamaican Dollar")
    public static let jod = Currency(code: "JOD", symbol: "JD", name: "Jordanian Dinar", minorUnits: 3)
    public static let jpy = Currency(code: "JPY", symbol: "¥", name: "Japanese Yen", minorUnits: 0)
    public static let kes = Currency(code: "KES", symbol: "KSh", name: "Kenyan Shilling")
    public static let kgs = Currency(code: "KGS", symbol: "сом", name: "Kyrgystani Som")
    public static let khr = Currency(code: "KHR", symbol: "៛", name: "Cambodian Riel")
    public static let kmf = Currency(code: "KMF", symbol: "CF", name: "Comorian Franc", minorUnits: 0)
    public static let kpw = Currency(code: "KPW", symbol: "₩", name: "North Korean Won")
    public static let krw = Currency(code: "KRW", symbol: "₩", name: "South Korean Won", minorUnits: 0)
    public static let kwd = Currency(code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar", minorUnits: 3)
    public static let kyd = Currency(code: "KYD", symbol: "$", name: "Cayman Islands Dollar")
    public static let kzt = Currency(code: "KZT", symbol: "₸", name: "Kazakhstani Tenge")
    public static let lak = Currency(code: "LAK", symbol: "₭", name: "Laotian Kip")
    public static let lbp = Currency(code: "LBP", symbol: "ل.ل", name: "Lebanese Pound")
    public static let lkr = Currency(code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee")
    public static let lrd = Currency(code: "LRD", symbol: "L$", name: "Liberian Dollar")
    public static let lsl = Currency(code: "LSL", symbol: "L", name: "Lesotho Loti")
    public static let lyd = Currency(code: "LYD", symbol: "ل.د", name: "Libyan Dinar", minorUnits: 3)
    public static let mad = Currency(code: "MAD", symbol: "MAD", name: "Moroccan Dirham")
    public static let mdl = Currency(code: "MDL", symbol: "L", name: "Moldovan Leu")
    public static let mga = Currency(code: "MGA", symbol: "Ar", name: "Malagasy Ariary")
    public static let mkd = Currency(code: "MKD", symbol: "ден", name: "Macedonian Denar")
    public static let mmk = Currency(code: "MMK", symbol: "K", name: "Myanmar Kyat")
    public static let mnt = Currency(code: "MNT", symbol: "₮", name: "Mongolian Tugrik")
    public static let mop = Currency(code: "MOP", symbol: "MOP$", name: "Macanese Pataca")
    public static let mru = Currency(code: "MRU", symbol: "UM", name: "Mauritanian Ouguiya")
    public static let mur = Currency(code: "MUR", symbol: "₨", name: "Mauritian Rupee")
    public static let mvr = Currency(code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa")
    public static let mwk = Currency(code: "MWK", symbol: "MK", name: "Malawian Kwacha")
    public static let mxn = Currency(code: "MXN", symbol: "MX$", name: "Mexican Peso")
    public static let myr = Currency(code: "MYR", symbol: "RM", name: "Malaysian Ringgit")
    public static let mzn = Currency(code: "MZN", symbol: "MT", name: "Mozambican Metical")
    public static let nad = Currency(code: "NAD", symbol: "N$", name: "Namibian Dollar")
    public static let ngn = Currency(code: "NGN", symbol: "₦", name: "Nigerian Naira")
    public static let nio = Currency(code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba")
    public static let nok = Currency(code: "NOK", symbol: "kr", name: "Norwegian Krone")
    public static let npr = Currency(code: "NPR", symbol: "₨", name: "Nepalese Rupee")
    public static let nzd = Currency(code: "NZD", symbol: "NZ$", name: "New Zealand Dollar")
    public static let omr = Currency(code: "OMR", symbol: "ر.ع.", name: "Omani Rial", minorUnits: 3)
    public static let pab = Currency(code: "PAB", symbol: "B/.", name: "Panamanian Balboa")
    public static let pen = Currency(code: "PEN", symbol: "S/.", name: "Peruvian Sol")
    public static let pgk = Currency(code: "PGK", symbol: "K", name: "Papua New Guinean Kina")
    public static let php = Currency(code: "PHP", symbol: "₱", name: "Philippine Peso")
    public static let pkr = Currency(code: "PKR", symbol: "₨", name: "Pakistani Rupee")
    public static let pln = Currency(code: "PLN", symbol: "zł", name: "Polish Zloty")
    public static let pyg = Currency(code: "PYG", symbol: "₲", name: "Paraguayan Guarani", minorUnits: 0)
    public static let qar = Currency(code: "QAR", symbol: "ر.ق", name: "Qatari Rial")
    public static let ron = Currency(code: "RON", symbol: "lei", name: "Romanian Leu")
    public static let rsd = Currency(code: "RSD", symbol: "din.", name: "Serbian Dinar")
    public static let rub = Currency(code: "RUB", symbol: "₽", name: "Russian Ruble")
    public static let rwf = Currency(code: "RWF", symbol: "RF", name: "Rwandan Franc", minorUnits: 0)
    public static let sar = Currency(code: "SAR", symbol: "ر.س", name: "Saudi Riyal")
    public static let sbd = Currency(code: "SBD", symbol: "SI$", name: "Solomon Islands Dollar")
    public static let scr = Currency(code: "SCR", symbol: "₨", name: "Seychellois Rupee")
    public static let sdg = Currency(code: "SDG", symbol: "ج.س.", name: "Sudanese Pound")
    public static let sek = Currency(code: "SEK", symbol: "kr", name: "Swedish Krona")
    public static let sgd = Currency(code: "SGD", symbol: "S$", name: "Singapore Dollar")
    public static let shp = Currency(code: "SHP", symbol: "£", name: "Saint Helena Pound")
    public static let sle = Currency(code: "SLE", symbol: "Le", name: "Sierra Leonean Leone")
    public static let sos = Currency(code: "SOS", symbol: "Sh", name: "Somali Shilling")
    public static let srd = Currency(code: "SRD", symbol: "Sr$", name: "Surinamese Dollar")
    public static let ssp = Currency(code: "SSP", symbol: "£", name: "South Sudanese Pound")
    public static let stn = Currency(code: "STN", symbol: "Db", name: "São Tomé and Príncipe Dobra")
    public static let svc = Currency(code: "SVC", symbol: "₡", name: "Salvadoran Colón")
    public static let syp = Currency(code: "SYP", symbol: "£S", name: "Syrian Pound")
    public static let szl = Currency(code: "SZL", symbol: "E", name: "Swazi Lilangeni")
    public static let thb = Currency(code: "THB", symbol: "฿", name: "Thai Baht")
    public static let tjs = Currency(code: "TJS", symbol: "SM", name: "Tajikistani Somoni")
    public static let tmt = Currency(code: "TMT", symbol: "T", name: "Turkmenistani Manat")
    public static let tnd = Currency(code: "TND", symbol: "د.ت", name: "Tunisian Dinar", minorUnits: 3)
    public static let top = Currency(code: "TOP", symbol: "T$", name: "Tongan Paʻanga")
    public static let `try` = Currency(code: "TRY", symbol: "₺", name: "Turkish Lira")
    public static let ttd = Currency(code: "TTD", symbol: "TT$", name: "Trinidad & Tobago Dollar")
    public static let twd = Currency(code: "TWD", symbol: "NT$", name: "New Taiwan Dollar")
    public static let tzs = Currency(code: "TZS", symbol: "TSh", name: "Tanzanian Shilling")
    public static let uah = Currency(code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia")
    public static let ugx = Currency(code: "UGX", symbol: "USh", name: "Ugandan Shilling", minorUnits: 0)
    public static let usd = Currency(code: "USD", symbol: "$", name: "US Dollar")
    public static let uyu = Currency(code: "UYU", symbol: "$U", name: "Uruguayan Peso")
    public static let uzs = Currency(code: "UZS", symbol: "сўм", name: "Uzbekistani Som")
    public static let ves = Currency(code: "VES", symbol: "Bs.S", name: "Venezuelan Bolívar Soberano")
    public static let vnd = Currency(code: "VND", symbol: "₫", name: "Vietnamese Dong", minorUnits: 0)
    public static let vuv = Currency(code: "VUV", symbol: "VT", name: "Vanuatu Vatu", minorUnits: 0)
    public static let wst = Currency(code: "WST", symbol: "WS$", name: "Samoan Tala")
    public static let xaf = Currency(code: "XAF", symbol: "FCFA", name: "Central African CFA Franc", minorUnits: 0)
    public static let xcd = Currency(code: "XCD", symbol: "EC$", name: "East Caribbean Dollar")
    public static let xof = Currency(code: "XOF", symbol: "CFA", name: "West African CFA Franc", minorUnits: 0)
    public static let xpf = Currency(code: "XPF", symbol: "₣", name: "CFP Franc", minorUnits: 0)
    public static let yer = Currency(code: "YER", symbol: "﷼", name: "Yemeni Rial")
    public static let zar = Currency(code: "ZAR", symbol: "R", name: "South African Rand")
    public static let zmw = Currency(code: "ZMW", symbol: "ZK", name: "Zambian Kwacha")
    public static let zwl = Currency(code: "ZWL", symbol: "Z$", name: "Zimbabwean Dollar")

    /// All known currencies.
    public static let allCurrencies: [Currency] = [
        .aed, .afn, .allLek, .amd, .ang, .aoa, .ars, .aud, .awg, .azn,
        .bam, .bbd, .bdt, .bgn, .bhd, .bif, .bmd, .bnd, .bob, .brl,
        .bsd, .btn, .bwp, .byn, .bzd,
        .cad, .cdf, .chf, .clp, .cny, .cop, .crc, .cup, .cve, .czk,
        .djf, .dkk, .dop, .dzd,
        .egp, .ern, .etb, .eur,
        .fjd, .fkp,
        .gbp, .gel, .ghs, .gip, .gmd, .gnf, .gtq, .gyd,
        .hkd, .hnl, .hrk, .htg, .huf,
        .idr, .ils, .inr, .iqd, .irr, .isk,
        .jmd, .jod, .jpy,
        .kes, .kgs, .khr, .kmf, .kpw, .krw, .kwd, .kyd, .kzt,
        .lak, .lbp, .lkr, .lrd, .lsl, .lyd,
        .mad, .mdl, .mga, .mkd, .mmk, .mnt, .mop, .mru, .mur, .mvr, .mwk, .mxn, .myr, .mzn,
        .nad, .ngn, .nio, .nok, .npr, .nzd,
        .omr,
        .pab, .pen, .pgk, .php, .pkr, .pln, .pyg,
        .qar,
        .ron, .rsd, .rub, .rwf,
        .sar, .sbd, .scr, .sdg, .sek, .sgd, .shp, .sle, .sos, .srd, .ssp, .stn, .svc, .syp, .szl,
        .thb, .tjs, .tmt, .tnd, .top, .try, .ttd, .twd, .tzs,
        .uah, .ugx, .usd, .uyu, .uzs,
        .ves, .vnd, .vuv,
        .wst,
        .xaf, .xcd, .xof, .xpf,
        .yer,
        .zar, .zmw, .zwl,
    ]
}
